#!/bin/tclsh 
source header.tcl
source proc.tcl

set design_path "design"
set random_design_path "random_test_cases"
set compile_rep_dir "report_compile"
set power_rep_dir "report_power"
set area_rep_dir "report_area"
set timing_rep_dir "report_timing"

set design_path "design"
set design_name "t1.v"
set clk_period 10

#load my design
#prototype | read_file -format FILETYPE FILENAME |
#echo design_name $design_name
#
#echo read_file_start
#read_file -format verilog ./$design_path/$design_name > /dev/null
#echo read_file_end
#
#echo get_lowest_clk_period_start
#while { 1 } {
#    #set clk
#    create_clock -name clk -period $clk_period { clk }
#
#    #compile
#    compile -map_effort high -boundary_optimization > ./$compile_rep_dir/$design_name.report
#
#    #report timing
#    report_timing > ./$timing_rep_dir/$design_name.report
#
#    #get slack
#    set slack [ exec bash -c "./get_slack $design_name.report" ]
#    echo slack $slack
#    if { $slack == 0.00 } {
#        echo get_lowest_clk_period
#        break
#    } else {
#        echo not_enough_low_clk_period
#        set clk_period [ expr $clk_period - $slack ]
#    }
#}
#echo get_lowest_clk_period_end

set round 1000
set i 0
echo gen_random_test_cases
while { $i < $round } {
    echo gen_case$i
    exec bash -c "./random_state_assignment_with_list $design_path $design_name $i"
    set gen_design_name case$i.v
    echo using_$gen_design_name

    remove_design -all
    echo read_file_start
    read_file -format verilog ./$random_design_path/$gen_design_name > /dev/null 
    echo read_file_end
    
    set clk_period 10
    echo get_lowest_clk_period_start
    while { 1 } {
        #set clk
        create_clock -name clk -period $clk_period { clk }
    
        #compile
        compile -map_effort high -boundary_optimization > ./$compile_rep_dir/$gen_design_name.report
    
        #report timing
        report_timing > ./$timing_rep_dir/$gen_design_name.report
    
        #get slack
        set slack [ exec bash -c "./get_slack $gen_design_name.report" ]
        echo slack $slack
        if { $slack == 0.00 } {
            echo get_lowest_clk_period
            report_area > ./$area_rep_dir/$gen_design_name.report
            report_power > ./$power_rep_dir/$gen_design_name.report
            break
        } else {
            echo not_enough_low_clk_period
            set clk_period [ expr $clk_period - $slack ]
        }
    }
    echo get_lowest_clk_period_end
    
    incr i
}

exit
