#!/bin/bash

#counting the range of random number
sc=$(($(./state_count $1 $2)+1))
function log2 {
    local x=0
    for (( y=$1-1 ; $y > 0; y >>= 1 )) ; do
        let x=$x+1
    done
    echo $x
}
expon=$(log2 $sc)
rpn=$(($(echo 2^$expon | bc)-1))

#generate a array, its size fits sc, and in random order 
random_list=$(shuf -i 0-$rpn | head -$sc) 

#get input width
input_width=$(($(cat design/t1.v | sed -n 's/input\s\+\[\([0-9]\+\):.*$/\1/p')+1))

#generate the parameter part with the random_list
stringarr=($random_list)
var="" 
i=0
for x in ${stringarr[@]}; do 
    var=${var}S$i'='$input_width\'d$x,\
    i=$((i+1))
    if [ $(($i%5)) == 0 ] 
    then
        var=$var'\n'
    fi
done
var=parameter\ $var
var=$(echo $var | sed 's/\(.*\)\(\,\)$/\1\;/g') 
#get the line number of the matched pattern
line_number=$(cat design/t1.v | grep 'para' -n | sed -n 's/\(:.*\)$//p')

#show the replaced design
cat design/t1.v | sed -e '/para/,/\;/d' | sed "${line_number}i${var}" | sed "s/module .*(/module case${3}(/g" > random_test_cases/case$3.v

